from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import user_passes_test
from django.urls import path

from . import accounts, finance, hr, operations, public, records, views

app_name = "webcom"

staff_required = user_passes_test(lambda user: user.is_authenticated and user.is_staff, login_url="webcom:login")

urlpatterns = [
    path("", public.public_home, name="public_home"),
    path("system/health/", views.system_health, name="system_health"),
    path("staff/login/", auth_views.LoginView.as_view(template_name="webCom/login.html"), name="login"),
    path("staff/forgot-password/", accounts.forgot_password, name="forgot_password"),
    path("staff/password-expired/", accounts.password_expired, name="password_expired"),
    path("staff/logout/", auth_views.LogoutView.as_view(next_page="webcom:public_home"), name="logout"),
    path("who-we-are/", public.public_page, {"page": "who-we-are"}, name="who_we_are"),
    path("what-we-do/", public.public_page, {"page": "what-we-do"}, name="what_we_do"),
    path("where-we-work/", public.public_page, {"page": "where-we-work"}, name="where_we_work"),
    path("impact/", public.public_page, {"page": "impact"}, name="impact"),
    path("resources/", public.public_page, {"page": "resources"}, name="resources"),
    path("careers/", public.careers, name="careers"),
    path("careers/<int:pk>/", public.job_detail, name="job_detail"),
    path("dashboard/", staff_required(views.home), name="home"),
    path("staff/password-management/", staff_required(accounts.password_management), name="password_management"),
    path("staff/password-management/<int:user_id>/", staff_required(accounts.password_management_action), name="password_management_action"),
    path("deployments/upload-roster/", staff_required(operations.duty_roster_upload), name="duty_roster_upload"),
    path("deployments/export-roster/", staff_required(operations.duty_roster_export), name="duty_roster_export"),
    path("contracts/<int:pk>/report/", staff_required(operations.contract_report), name="contract_report"),
    path("salaries/<int:pk>/payslip/", staff_required(finance.salary_payslip), name="salary_payslip"),
    path("invoices/<int:pk>/invoice/", staff_required(finance.invoice_document), name="invoice_document"),
    path("payments/<int:pk>/receipt/", staff_required(finance.payment_receipt), name="payment_receipt"),
    path("payments/<int:pk>/reconciliation/", staff_required(finance.payment_reconciliation), name="payment_reconciliation"),
    path("purchase-orders/<int:pk>/lpo/", staff_required(finance.purchase_order_lpo_report), name="purchase_order_lpo_report"),
    path("training/<int:pk>/certificate/", staff_required(hr.training_certificate), name="training_certificate"),
    path("job-applications/<int:pk>/resume/", staff_required(hr.job_application_resume), name="job_application_resume"),
    path("leaves/<int:pk>/review/", staff_required(hr.leave_review), name="leave_review"),
    path("leaves/notifications/", staff_required(hr.leave_notifications), name="leave_notifications"),
    path("leaves/notifications/<int:notification_id>/<str:action>/", staff_required(hr.leave_notification_action), name="leave_notification_action"),
    path("employees/<int:pk>/transfer/", staff_required(hr.employee_transfer), name="employee_transfer"),
    path("incidents/report/", staff_required(operations.incident_report), name="incident_report"),
    path("incidents/notifications/", staff_required(operations.incident_notifications), name="incident_notifications"),
    path("incidents/<int:pk>/manage/", staff_required(operations.incident_manage), name="incident_manage"),
    path("incidents/<int:pk>/investigation-report/", staff_required(operations.incident_investigation_report), name="incident_investigation_report"),
    path("disciplinary-actions/notifications/", staff_required(hr.disciplinary_notifications), name="disciplinary_notifications"),
    path("budgets/report/", staff_required(finance.budget_report), name="budget_report"),
    path("budgets/notifications/", staff_required(finance.budget_report), name="budget_notifications"),
    path("expenses/report/", staff_required(finance.expense_report), name="expense_report"),
    path("expenses/notifications/", staff_required(finance.expense_report), name="expense_notifications"),
    path("finance/aging-report/", staff_required(finance.aging_report), name="aging_report"),
    path("api/procurement/", staff_required(finance.procurement_api_index), name="procurement_api_index"),
    path("api/payouts/", staff_required(finance.payout_api_index), name="payout_api_index"),
    path("api/payouts/<str:batch_type>/", staff_required(finance.payout_api_batch), name="payout_api_batch"),
    path("api/procurement/<str:model_name>/", staff_required(finance.procurement_api_list), name="procurement_api_list"),
    path("api/procurement/<str:model_name>/<int:pk>/", staff_required(finance.procurement_api_detail), name="procurement_api_detail"),
    path("api/incidents/<int:pk>/notify/", staff_required(operations.incident_notify_api), name="incident_notify_api"),
    path("api/sites/<int:pk>/deployment-area-guards/", staff_required(operations.site_deployment_area_guards_api), name="site_deployment_area_guards_api"),
    path("incidents/<int:pk>/notify/", staff_required(operations.incident_notify), name="incident_notify"),
    path("procurement-requisitions/<int:pk>/contact-supplier/", staff_required(finance.procurement_contact_supplier), name="procurement_contact_supplier"),
    path("asset-assignments/report/", staff_required(operations.asset_assignment_report), name="asset_assignment_report"),
    path("assets/report/", staff_required(operations.asset_store_report), name="asset_store_report"),
    path("assets/group/", staff_required(operations.asset_group_detail), name="asset_group_detail"),
    path("assets/issued-out/", staff_required(operations.asset_issued_out_detail), name="asset_issued_out_detail"),
    path("<str:model_name>/", staff_required(records.model_list), name="list"),
    path("<str:model_name>/add/", staff_required(records.model_create), name="create"),
    path("<str:model_name>/import/", staff_required(records.model_import), name="import"),
    path("<str:model_name>/export/", staff_required(records.model_export), name="export"),
    path("<str:model_name>/<int:pk>/", staff_required(records.model_detail), name="detail"),
    path("<str:model_name>/<int:pk>/edit/", staff_required(records.model_update), name="update"),
    path("<str:model_name>/<int:pk>/delete/", staff_required(records.model_delete), name="delete"),
]

