import os
"""
Django settings for SecurityCompany project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlparse

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
IS_VERCEL = bool(os.environ.get("VERCEL") or os.environ.get("VERCEL_ENV") or os.environ.get("VERCEL_URL") or os.environ.get("VERCEL_REGION"))
IS_VERCEL_RUNTIME = IS_VERCEL


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or os.environ.get("SECRET_KEY") or "django-insecure-local-development-only-change-me"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", not IS_VERCEL)
REQUIRE_PRODUCTION_CONFIG = not DEBUG and (not IS_VERCEL or IS_VERCEL_RUNTIME)
VERCEL_CONFIGURATION_ERRORS = []

ALLOWED_HOSTS = [host.strip() for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if host.strip()]
if os.environ.get("VERCEL") and ".vercel.app" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(".vercel.app")
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]
for host in ALLOWED_HOSTS:
    if host.startswith("."):
        CSRF_TRUSTED_ORIGINS.append(f"https://*{host}")
    elif host not in {"localhost", "127.0.0.1"}:
        CSRF_TRUSTED_ORIGINS.append(f"https://{host}")
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))
if REQUIRE_PRODUCTION_CONFIG:
    if SECRET_KEY == "django-insecure-local-development-only-change-me":
        if IS_VERCEL_RUNTIME:
            VERCEL_CONFIGURATION_ERRORS.append("DJANGO_SECRET_KEY must be set to a real production secret.")
        else:
            raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set in production.")
    if not ALLOWED_HOSTS or "*" in ALLOWED_HOSTS:
        if IS_VERCEL_RUNTIME:
            VERCEL_CONFIGURATION_ERRORS.append("DJANGO_ALLOWED_HOSTS must list explicit production hosts.")
        else:
            raise ImproperlyConfigured("DJANGO_ALLOWED_HOSTS must list explicit production hosts.")

SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", not DEBUG)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "31536000" if not DEBUG else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", not DEBUG)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", not DEBUG)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
X_FRAME_OPTIONS = "SAMEORIGIN"
SECURE_REFERRER_POLICY = "same-origin"
AUDIT_LOG_ENABLED = env_bool("DJANGO_AUDIT_LOG_ENABLED", True)
EMPLOYEE_DEFAULT_PASSWORD = os.environ.get("EMPLOYEE_DEFAULT_PASSWORD", "ChangeMe123!")
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get("DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE", str(5 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get("DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE", str(5 * 1024 * 1024)))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "webCom",
]
MIDDLEWARE = [
    'webCom.middleware.VercelConfigurationMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'webCom.middleware.PasswordExpiryMiddleware',
    'webCom.middleware.RequestAuditMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SecurityCompany.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SecurityCompany.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL_PLACEHOLDERS = {
    "<your postgresql connection string>",
    "<hosted postgres connection string>",
    "paste-real-postgres-url-here",
    "postgresql://user:password@host/database?sslmode=require",
    "postgresql://username:password@hostname/database_name?sslmode=require",
}
VALID_DATABASE_SCHEMES = {"postgres", "postgresql", "pgsql", "postgis", "timescale", "timescalegis", "sqlite"}


def normalize_database_url(database_url):
    database_url = database_url.strip().strip("\"'")
    for prefix in ("DATABASE_URL=", "POSTGRES_URL=", "POSTGRES_URL_NON_POOLING="):
        if database_url.upper().startswith(prefix):
            return database_url[len(prefix):].strip().strip("\"'")
    for scheme in ("postgresql://", "postgres://", "pgsql://", "postgis://", "timescale://", "timescalegis://", "sqlite://"):
        scheme_index = database_url.lower().find(scheme)
        if scheme_index >= 0:
            return database_url[scheme_index:].split()[0].strip().strip("\"'")
    return database_url


def invalid_database_url_reason(name, database_url):
    lowered_url = database_url.lower()
    is_placeholder = (
        lowered_url in DATABASE_URL_PLACEHOLDERS
        or "paste-real" in lowered_url
        or "username:password@hostname" in lowered_url
        or "user:password@host" in lowered_url
        or "<your" in lowered_url
        or "<hosted" in lowered_url
    )
    scheme = urlparse(database_url).scheme
    if is_placeholder:
        return f"{name} is still placeholder text. Replace it with a real hosted PostgreSQL connection string."
    if scheme not in VALID_DATABASE_SCHEMES:
        return f"{name} must be a real database URL, for example postgresql://user:password@host/database?sslmode=require."
    if IS_VERCEL_RUNTIME and scheme == "sqlite":
        return f"{name} must point to hosted PostgreSQL on Vercel. SQLite is only supported for local development."
    return ""


def configured_database_url():
    invalid_reasons = []
    for name in ("DATABASE_URL", "POSTGRES_URL", "POSTGRES_URL_NON_POOLING"):
        database_url = normalize_database_url(os.environ.get(name) or "")
        if not database_url:
            continue
        invalid_reason = invalid_database_url_reason(name, database_url)
        if invalid_reason:
            invalid_reasons.append(invalid_reason)
            continue
        return database_url

    if invalid_reasons:
        message = " ".join(invalid_reasons)
        if IS_VERCEL_RUNTIME:
            VERCEL_CONFIGURATION_ERRORS.append(message)
            return ""
        raise ImproperlyConfigured(message)

    return ""

DATABASE_ENV_WAS_PROVIDED = any(
    (os.environ.get(name) or "").strip()
    for name in ("DATABASE_URL", "POSTGRES_URL", "POSTGRES_URL_NON_POOLING")
)
DATABASE_URL = configured_database_url()
if DATABASE_URL:
    os.environ["DATABASE_URL"] = DATABASE_URL
else:
    os.environ.pop("DATABASE_URL", None)

SQLITE_DATABASE_PATH = BASE_DIR / "db.sqlite3"
DATABASE_CONN_MAX_AGE = int(os.environ.get("DATABASE_CONN_MAX_AGE", "600"))
DATABASE_SSL_REQUIRE = env_bool("DATABASE_SSL_REQUIRE", True)

if IS_VERCEL_RUNTIME and not DATABASE_URL and not DATABASE_ENV_WAS_PROVIDED:
    VERCEL_CONFIGURATION_ERRORS.append(
        "DATABASE_URL must be set to a hosted PostgreSQL connection string. SQLite is not supported on Vercel."
    )

database_config = (
    dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=DATABASE_CONN_MAX_AGE,
        conn_health_checks=True,
    )
    if DATABASE_URL
    else dj_database_url.parse(
        f"sqlite:///{SQLITE_DATABASE_PATH}",
        conn_max_age=DATABASE_CONN_MAX_AGE,
        conn_health_checks=True,
    )
)

if DATABASE_URL and database_config["ENGINE"] != "django.db.backends.sqlite3" and DATABASE_SSL_REQUIRE:
    database_config.setdefault("OPTIONS", {})
    database_config["OPTIONS"].setdefault("sslmode", "require")

DATABASES = {
    "default": database_config
}

if REQUIRE_PRODUCTION_CONFIG and not IS_VERCEL_RUNTIME and DATABASES["default"]["ENGINE"] == "django.db.backends.sqlite3":
    raise ImproperlyConfigured("DATABASE_URL must be set in production.")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
WHITENOISE_MANIFEST_STRICT = env_bool("WHITENOISE_MANIFEST_STRICT", not IS_VERCEL_RUNTIME)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

COMPANY_NAME = "TURYANS SECURITY COMPANY (U) LIMITED"
# Email notification settings
# To send real emails, set EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER,
# EMAIL_HOST_PASSWORD, and DEFAULT_FROM_EMAIL in the environment.

EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND")
if not EMAIL_BACKEND:
    EMAIL_BACKEND = (
        "django.core.mail.backends.smtp.EmailBackend"
        if os.environ.get("EMAIL_HOST")
        else "django.core.mail.backends.console.EmailBackend"
    )
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@turyans-security.local")
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "10"))


LOGIN_URL = '/staff/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'


