# Generated by Django 6.0.7 on 2026-08-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0068_employee_payout_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('resigned', 'Resigned'), ('dismissed', 'Dismissed'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
    ]
