# Generated by Django 6.0.7 on 2026-08-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0068_employee_payout_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='number_of_guards',
        ),
    ]
