# Generated by Django 6.0.7 on 2026-09-01 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0070_userpasswordprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='address_while_away',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leave',
            name='application_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='leave',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='leave',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_leave_applications', to='webCom.employee'),
        ),
        migrations.AddField(
            model_name='leave',
            name='hr_verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_verified_leave_applications', to='webCom.employee'),
        ),
        migrations.AddField(
            model_name='leave',
            name='stand_in_coworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stand_in_leave_applications', to='webCom.employee'),
        ),
        migrations.AddField(
            model_name='leave',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_leave_applications', to='webCom.employee'),
        ),
    ]
