# Generated by Django 6.0.7 on 2026-09-01 11:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0071_leave_address_while_away_leave_application_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_group', models.CharField(max_length=50)),
                ('notification_type', models.CharField(choices=[('verification_requested', 'Verification Requested'), ('approval_requested', 'Approval Requested'), ('coverage_notice', 'Coverage Notice'), ('leave_verified', 'Leave Verified'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected')], max_length=40)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('read', 'Read'), ('actioned', 'Actioned')], default='pending', max_length=20)),
                ('decision', models.CharField(blank=True, default='', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='webCom.leave')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_notifications', to='webCom.employee')),
            ],
            options={
                'db_table': 'leave_notifications',
                'ordering': ['-notified_at', '-notification_id'],
                'constraints': [models.UniqueConstraint(fields=('leave', 'recipient', 'recipient_group', 'notification_type'), name='unique_leave_notification')],
            },
        ),
    ]
