# Generated by Django 6.0.7 on 2026-09-01 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0072_leavenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetassignment',
            name='accountability_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='accountability_status',
            field=models.CharField(choices=[('pending_acknowledgement', 'Pending Acknowledgement'), ('acknowledged', 'Acknowledged'), ('cleared', 'Cleared'), ('escalated', 'Escalated')], default='pending_acknowledgement', max_length=30),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='condition_issued',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='condition_returned',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_asset_assignments', to='webCom.employee'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_asset_assignments', to='webCom.employee'),
        ),
    ]
