# Generated by Django 6.0.7 on 2026-09-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0073_assetassignment_accountability_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='color',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='asset',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='make',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='police_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='size',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='asset',
            name='storage_location',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
