# Generated by Django 6.0.7 on 2026-09-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0074_asset_color_asset_condition_asset_make_asset_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='chassis_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='engine_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='number_plate',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
