# Generated by Django 6.0.7 on 2026-09-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0075_asset_chassis_number_asset_engine_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='affected_items_details',
            field=models.TextField(blank=True, default='', help_text='Enter one item per line. Use: item | serial number | engraved number.'),
        ),
        migrations.AddField(
            model_name='incident',
            name='alleged_stolen_items',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='commencement_of_investigations',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='guards_on_duty',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='police_case_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='suspects',
            field=models.TextField(blank=True, default=''),
        ),
    ]
