# Generated by Django 6.0.7 on 2026-09-02 12:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0077_assign_jinja_sites_to_greater_jinja'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_group', models.CharField(default='Human Resource', max_length=50)),
                ('notification_type', models.CharField(default='new_application', max_length=40)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('delivery_note', models.CharField(blank=True, default='', max_length=255)),
                ('notified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='webCom.jobapplication')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application_notifications', to='webCom.employee')),
            ],
            options={
                'db_table': 'job_application_notifications',
                'ordering': ['-notified_at', '-notification_id'],
                'constraints': [models.UniqueConstraint(fields=('application', 'recipient', 'notification_type'), name='unique_job_application_notification')],
            },
        ),
    ]
